"""empty message

Revision ID: 1ad9391a7f1b
Revises: beeab36df702
Create Date: 2017-03-18 12:09:12.517205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad9391a7f1b'
down_revision = 'beeab36df702'
branch_labels = None
depends_on = None


def upgrade():

    ## DOING A BLANK UPGRADE FOR NOW, SANITY ERROR CHECK FOR JOSIE 
    ## Given the errors that were happening with jsonify in app.py
    pass

    # # Step 1 - drop old unique index for houses (it wasn't actually unique)
    # op.drop_unique_constraint('uq_Houses_Latitude_Longitude_Address2', table_name='Houses', schema='OurHouse')
    # op.drop_index('ix_Houses_Latitude_Longitude_Address2', table_name='Houses', schema='OurHouse')

    # # Step 2 - create new unique index for houses
    # op.create_unique_constraint('uq_Houses_Latitude_Longitude_Address1_Address2', 'Houses', ['Latitude', 'Longitude', 'Address1', 'Address2'], schema='OurHouse')
    # op.create_index('ix_Houses_Latitude_Longitude_Address1_Address2', 'Houses', ['Latitude', 'Longitude', 'Address1', 'Address2'], unique=True, schema='OurHouse')

    # # Step 3 - add new columns 'DateAvailable' and 'LeaseTerm' to houses
    # # op.create_column 
    # # sa.Column('DateAvailable', sa.Date(), nullable=True)
    # # sa.Column('LeaseTerm', sa.SmallInteger(), nullable=True)    

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_OurHouse_Reviews_StudentId'), table_name='Reviews', schema='OurHouse')
    op.drop_index(op.f('ix_OurHouse_Reviews_HouseId'), table_name='Reviews', schema='OurHouse')
    op.drop_table('Reviews', schema='OurHouse')
    op.drop_index(op.f('ix_OurHouse_Houses_LandlordId'), table_name='Houses', schema='OurHouse')
    op.drop_index('ix_Houses_Latitude_Longitude_Address1_Address2', table_name='Houses', schema='OurHouse')
    op.drop_table('Houses', schema='OurHouse')
    op.drop_index('ix_Students_Email', table_name='Students', schema='OurHouse')
    op.drop_table('Students', schema='OurHouse')
    op.drop_index('ix_Landlords_Email', table_name='Landlords', schema='OurHouse')
    op.drop_table('Landlords', schema='OurHouse')
    # ### end Alembic commands ###
