"""empty message

Revision ID: 24638650ef53
Revises: eb8ee27d5afa
Create Date: 2017-03-02 15:52:24.692995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24638650ef53'
down_revision = 'eb8ee27d5afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_unique_constraint('uq_Students_Email', 'Students', ['Email'], schema='OurHouse')
    op.create_index('ix_Students_Email', 'Students', ['Email'], schema='OurHouse', unique=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_OurHouse_Reviews_StudentId'), table_name='Reviews', schema='OurHouse')
    op.drop_index(op.f('ix_OurHouse_Reviews_HouseId'), table_name='Reviews', schema='OurHouse')
    op.drop_table('Reviews', schema='OurHouse')
    op.drop_index(op.f('ix_OurHouse_Houses_LandlordId'), table_name='Houses', schema='OurHouse')
    op.drop_table('Houses', schema='OurHouse')
    op.drop_table('Students', schema='OurHouse')
    op.drop_table('Landlords', schema='OurHouse')
    # ### end Alembic commands ###
