"""empty message

Revision ID: 467f9e2497f6
Revises: e67234824c93
Create Date: 2017-04-06 22:08:58.909164

"""
from alembic import op
import sqlalchemy as sa
from flask_store.sqla import FlaskStoreType
# from flask_store import Store


# revision identifiers, used by Alembic.
revision = '467f9e2497f6'
down_revision = 'e67234824c93'
branch_labels = None
depends_on = None


def upgrade():

    op.create_table('Photos',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('HouseId', sa.Integer(), nullable=False),
    sa.Column('RelativePath', FlaskStoreType(length=256), nullable=False),
    sa.Column('CreatedAt', sa.DateTime(timezone=True), server_default=sa.func.current_timestamp(), nullable=False),
    sa.Column('UpdatedAt', sa.DateTime(timezone=True), server_default=sa.func.current_timestamp(), nullable=False),
    sa.ForeignKeyConstraint(['HouseId'], [u'OurHouse.Houses.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('RelativePath'),
    schema='OurHouse'
    )
    op.create_index(op.f('ix_Photos_HouseId'), 'Photos', ['HouseId'], unique=False, schema='OurHouse')
    op.create_index('ix_Photos_RelativePath', 'Photos', ['RelativePath'], unique=False, schema='OurHouse')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index('ix_Photos_RelativePath', table_name='Photos', schema='OurHouse')
    op.drop_index(op.f('ix_OurHouse_Photos_HouseId'), table_name='Photos', schema='OurHouse')
    op.drop_table('Photos', schema='OurHouse')

    # ### end Alembic commands ###
