"""empty message

Revision ID: 6734e11c10be
Revises: 1ad9391a7f1b
Create Date: 2017-03-22 21:16:12.844009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6734e11c10be'
down_revision = '1ad9391a7f1b'
branch_labels = None
depends_on = None


def upgrade():

    # Step 1 - drop old unique index for houses (it wasn't actually unique)
    op.drop_constraint('uq_Houses_Latitude_Longitude_Address2', table_name='Houses', type_='unique', schema='OurHouse')
    op.drop_index('ix_Houses_Latitude_Longitude_Address2', table_name='Houses', schema='OurHouse')

    # Step 2 - create new unique index for houses
    op.create_unique_constraint('uq_Houses_Latitude_Longitude_Address1_Address2', 'Houses', ['Latitude', 'Longitude', 'Address1', 'Address2'], schema='OurHouse')
    op.create_index('ix_Houses_Latitude_Longitude_Address1_Address2', 'Houses', ['Latitude', 'Longitude', 'Address1', 'Address2'], unique=True, schema='OurHouse')

    # Step 3 - add new columns 'DateAvailable' and 'LeaseTerm' to Houses table
    op.add_column('Houses', sa.Column('DateAvailable', sa.Date(), nullable=True), schema='OurHouse')
    op.add_column('Houses', sa.Column('DateAvailable', sa.Date(), nullable=True), schema='OurHouse')
    op.add_column('Houses', sa.Column('LeaseTerm', sa.SmallInteger(), nullable=True), schema='OurHouse') 


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_OurHouse_Reviews_StudentId'), table_name='Reviews', schema='OurHouse')
    op.drop_index(op.f('ix_OurHouse_Reviews_HouseId'), table_name='Reviews', schema='OurHouse')
    op.drop_table('Reviews', schema='OurHouse')
    op.drop_index(op.f('ix_OurHouse_Houses_LandlordId'), table_name='Houses', schema='OurHouse')
    op.drop_index('ix_Houses_Latitude_Longitude_Address1_Address2', table_name='Houses', schema='OurHouse')
    op.drop_table('Houses', schema='OurHouse')
    op.drop_index('ix_Students_Email', table_name='Students', schema='OurHouse')
    op.drop_table('Students', schema='OurHouse')
    op.drop_index('ix_Landlords_Email', table_name='Landlords', schema='OurHouse')
    op.drop_table('Landlords', schema='OurHouse')
    # ### end Alembic commands ###
