"""empty message

Revision ID: 71d653be103c
Revises: d10e56320fc1
Create Date: 2017-04-06 16:48:57.099526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import literal


# revision identifiers, used by Alembic.
revision = '71d653be103c'
down_revision = 'd10e56320fc1'
branch_labels = None
depends_on = None


def upgrade():

    # Step 1: add CreatedAt and UpdatedAt columns on 'Houses' table with a server default
    op.add_column('Houses', sa.Column('CreatedAt', sa.DateTime(timezone=True),
                     server_default=sa.func.current_timestamp(), nullable=False), schema='OurHouse')
    op.add_column('Houses', sa.Column('UpdatedAt', sa.DateTime(timezone=True),
                     server_default=sa.func.current_timestamp(), nullable=False), schema='OurHouse')

    # Step 2: add server defaults to CreatedAt and UpdatedAt columns on all existing columns
    op.alter_column('Students', 'CreatedAt',
                     server_default=sa.func.current_timestamp(), schema='OurHouse')
    op.alter_column('Students', 'UpdatedAt',
                     server_default=sa.func.current_timestamp(), schema='OurHouse')

    op.alter_column('Landlords', 'CreatedAt',
                     server_default=sa.func.current_timestamp(), schema='OurHouse')
    op.alter_column('Landlords', 'UpdatedAt',
                     server_default=sa.func.current_timestamp(), schema='OurHouse')

    op.alter_column('Developers', 'CreatedAt',
                     server_default=sa.func.current_timestamp(), schema='OurHouse')
    op.alter_column('Developers', 'UpdatedAt',
                     server_default=sa.func.current_timestamp(), schema='OurHouse')

    op.alter_column('Reviews', 'CreatedAt',
                     server_default=sa.func.current_timestamp(), schema='OurHouse')
    op.alter_column('Reviews', 'UpdatedAt',
                     server_default=sa.func.current_timestamp(), schema='OurHouse')

    # Step 3: Change the type of Stars column to a length of just 1 char
    op.alter_column('Reviews', 'Stars', type_=sa.String(length=1), schema='OurHouse')

    # Step 4: Add as 'IsActive' column to Houses table
    op.add_column('Houses', sa.Column('IsActive', sa.Boolean(), 
                    server_default=literal(True)), schema='OurHouse')

    # Step 5: Add server default to 'IsActive' column to Students and Landlords table
    op.alter_column('Students', 'IsActive', server_default=literal(True), schema='OurHouse')
    op.alter_column('Landlords', 'IsActive', server_default=literal(True), schema='OurHouse')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_OurHouse_Reviews_StudentId'), table_name='Reviews', schema='OurHouse')
    op.drop_index(op.f('ix_OurHouse_Reviews_HouseId'), table_name='Reviews', schema='OurHouse')
    op.drop_table('Reviews', schema='OurHouse')
    op.drop_index(op.f('ix_OurHouse_Houses_LandlordId'), table_name='Houses', schema='OurHouse')
    op.drop_index('ix_Houses_Latitude_Longitude_Address1_Address2', table_name='Houses', schema='OurHouse')
    op.drop_table('Houses', schema='OurHouse')
    op.drop_index('ix_Students_Email', table_name='Students', schema='OurHouse')
    op.drop_table('Students', schema='OurHouse')
    op.drop_index('ix_Landlords_Email', table_name='Landlords', schema='OurHouse')
    op.drop_table('Landlords', schema='OurHouse')
    op.drop_index('ix_Developers_Key', table_name='Developers', schema='OurHouse')
    op.drop_table('Developers', schema='OurHouse')
    # ### end Alembic commands ###
