"""empty message

Revision ID: a5f4dd3b3399
Revises: 467f9e2497f6
Create Date: 2017-04-15 15:41:54.298615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f4dd3b3399'
down_revision = '467f9e2497f6'
branch_labels = None
depends_on = None


def upgrade():

    ####### STEPS FOR STUDENTS TABLE AND PASSWORDS ######

    # Step 1: Add new column PasswordHash with 'nullable=True'
    op.add_column('Students', sa.Column('PasswordHash', sa.String(length=60), nullable=True), 
                    schema='OurHouse')

    # Step 2: Add default hashed-password 'admin' to all existing users
    #           '$2b$12$8tgR3A32FkDw6eoaqQn1Buyw6u/sKN6EraTFVKpAkk2uZPmxCZyLi'
    op.execute('UPDATE "OurHouse"."Students" SET "PasswordHash" = \'$2b$12$8tgR3A32FkDw6eoaqQn1Buyw6u/sKN6EraTFVKpAkk2uZPmxCZyLi\' WHERE "PasswordHash" IS NULL')

    # Step 3: Change the column PasswordHash with 'nullable=False'
    op.alter_column('Students', 'PasswordHash',
                     nullable=False, schema='OurHouse')

    # Step 4: Get rid of old <Email> index and replace with <Email, PasswordHash> index
    op.drop_index('ix_Students_Email', table_name='Students', schema='OurHouse')

    # Step 5: Add new <Email, PasswordHash> index
    op.create_index('ix_Students_Email_PasswordHash', 'Students', ['Email', 'PasswordHash'], unique=True, schema='OurHouse')
    

    ####### STEPS FOR LANDLORDS TABLE AND PASSWORDS ######

    # Step 1: Add new column PasswordHash with 'nullable=True'
    op.add_column('Landlords', sa.Column('PasswordHash', sa.String(length=60), nullable=True), 
                    schema='OurHouse')

    # Step 2: Add default hashed-password 'admin' to all existing users
    #           '$2b$12$8tgR3A32FkDw6eoaqQn1Buyw6u/sKN6EraTFVKpAkk2uZPmxCZyLi'
    op.execute('UPDATE "OurHouse"."Landlords" SET "PasswordHash" = \'$2b$12$8tgR3A32FkDw6eoaqQn1Buyw6u/sKN6EraTFVKpAkk2uZPmxCZyLi\' WHERE "PasswordHash" IS NULL')

    # Step 3: Change the column PasswordHash with 'nullable=False'
    op.alter_column('Landlords', 'PasswordHash',
                     nullable=False, schema='OurHouse')

    # Step 4: Get rid of old <Email> index and replace with <Email, PasswordHash> index
    op.drop_index('ix_Landlords_Email', table_name='Landlords', schema='OurHouse')

    # Step 5: Add new <Email, PasswordHash> index
    op.create_index('ix_Landlords_Email_PasswordHash', 'Landlords', ['Email', 'PasswordHash'], unique=True, schema='OurHouse')

    ############## OTHER LIL CHANGES #############

    # JK onupdate column does not exist on postgres

    # Step 1: Change all UpdatedAt columns to have onupdate=sa.func.current_timestamp()

    # op.alter_column('Houses', 'UpdatedAt',
    #                  onupdate=sa.func.current_timestamp(), schema='OurHouse')

    # op.alter_column('Students', 'UpdatedAt',
    #                  onupdate=sa.func.current_timestamp(), schema='OurHouse')

    # op.alter_column('Landlords', 'UpdatedAt',
    #                  onupdate=sa.func.current_timestamp(), schema='OurHouse')

    # op.alter_column('Reviews', 'UpdatedAt',
    #                  onupdate=sa.func.current_timestamp(), schema='OurHouse')

    # op.alter_column('Developers', 'UpdatedAt',
    #                  onupdate=sa.func.current_timestamp(), schema='OurHouse')

    # op.alter_column('Photos', 'UpdatedAt',
    #                  onupdate=sa.func.current_timestamp(), schema='OurHouse')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_OurHouse_Reviews_StudentId'), table_name='Reviews', schema='OurHouse')
    op.drop_index(op.f('ix_OurHouse_Reviews_HouseId'), table_name='Reviews', schema='OurHouse')
    op.drop_table('Reviews', schema='OurHouse')
    op.drop_index('ix_Photos_RelativePath', table_name='Photos', schema='OurHouse')
    op.drop_index(op.f('ix_OurHouse_Photos_HouseId'), table_name='Photos', schema='OurHouse')
    op.drop_table('Photos', schema='OurHouse')
    op.drop_index(op.f('ix_OurHouse_Houses_LandlordId'), table_name='Houses', schema='OurHouse')
    op.drop_index('ix_Houses_Latitude_Longitude_Address1_Address2', table_name='Houses', schema='OurHouse')
    op.drop_table('Houses', schema='OurHouse')
    op.drop_index('ix_Students_Email_PasswordHash', table_name='Students', schema='OurHouse')
    op.drop_table('Students', schema='OurHouse')
    op.drop_index('ix_Landlords_Email_PasswordHash', table_name='Landlords', schema='OurHouse')
    op.drop_table('Landlords', schema='OurHouse')
    op.drop_index('ix_Developers_Key', table_name='Developers', schema='OurHouse')
    op.drop_table('Developers', schema='OurHouse')
    # ### end Alembic commands ###
