"""empty message

Revision ID: d10e56320fc1
Revises: 98704b11ebd9
Create Date: 2017-04-04 16:12:52.835569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd10e56320fc1'
down_revision = '98704b11ebd9'
branch_labels = None
depends_on = None


def upgrade():

    # Step 1 - an index on 'Developer' table, 'Key' column for fast searching (unique key was already created)
    op.create_index('ix_Developers_Key', 'Developers', ['Key'], unique=True, schema='OurHouse')

    # Step 2 - update 'Reviews' table with 'Comment' column 4096 byte length
    #          add CreatedAt and UpdatedAt Columns
    op.drop_column('Reviews', 'Comment', schema='OurHouse') #drop old column
    op.add_column('Reviews', sa.Column('Comment', sa.String(length=4096), nullable=True), schema='OurHouse')
    op.add_column('Reviews', sa.Column('CreatedAt', sa.DateTime(timezone=True), nullable=False), schema='OurHouse')
    op.add_column('Reviews', sa.Column('UpdatedAt', sa.DateTime(timezone=True), nullable=False), schema='OurHouse')

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_OurHouse_Reviews_StudentId'), table_name='Reviews', schema='OurHouse')
    op.drop_index(op.f('ix_OurHouse_Reviews_HouseId'), table_name='Reviews', schema='OurHouse')
    op.drop_table('Reviews', schema='OurHouse')
    op.drop_index(op.f('ix_OurHouse_Houses_LandlordId'), table_name='Houses', schema='OurHouse')
    op.drop_index('ix_Houses_Latitude_Longitude_Address1_Address2', table_name='Houses', schema='OurHouse')
    op.drop_table('Houses', schema='OurHouse')
    op.drop_index('ix_Students_Email', table_name='Students', schema='OurHouse')
    op.drop_table('Students', schema='OurHouse')
    op.drop_index('ix_Landlords_Email', table_name='Landlords', schema='OurHouse')
    op.drop_table('Landlords', schema='OurHouse')
    op.drop_table('Developers', schema='OurHouse')
    # ### end Alembic commands ###
