"""empty message

Revision ID: df594fb2c577
Revises: 24638650ef53
Create Date: 2017-03-02 17:03:43.426378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df594fb2c577'
down_revision = '24638650ef53'
branch_labels = None
depends_on = None


def upgrade():

    ## Create Landlords constraints and indexes
    op.create_unique_constraint('uq_Landlords_Email', 'Landlords', ['Email'], schema='OurHouse')
    op.create_index('ix_Landlords_Email', 'Landlords', ['Email'], schema='OurHouse', unique=True)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_OurHouse_Reviews_StudentId'), table_name='Reviews', schema='OurHouse')
    op.drop_index(op.f('ix_OurHouse_Reviews_HouseId'), table_name='Reviews', schema='OurHouse')
    op.drop_table('Reviews', schema='OurHouse')
    op.drop_index(op.f('ix_OurHouse_Houses_LandlordId'), table_name='Houses', schema='OurHouse')
    op.drop_table('Houses', schema='OurHouse')
    op.drop_table('Students', schema='OurHouse')
    op.drop_table('Landlords', schema='OurHouse')
    # ### end Alembic commands ###
